### ISSUE TITLE
AlekId's patch

### ISSUE THREAD

**Issue by Alexey-T** [Alexey-T/ATSynEdit_Ex#5]
```
@@ -360,6 +367,8 @@ procedure TATAdapterEControl.OnEditorCalcHilite(Sender: TObject;
begin
  if not Assigned(AnClient) then Exit;
  DoCheckEditorList;
  if ALineIndex > AnClient.LastAppendedPoint.Y then
     UpdateData(false, true);
```

в OnEditorCalcHilite.

нельзя так делать- эта ф-ця не должна делать побочные эфекты. К тому же вызывается часто - 30 раз если на экране 30 строк. И "if ALineIndex> ..." сработает к раз на одну строку если строка wrapped.
@AlekId

**Comment by Alexey-T** [comment]
```
procedure TATAdapterEControl.InvalidateEditors;
var
  edit: Pointer;
begin
  for edit in  EdList do begin
    if assigned(edit) and (TObject(edit) is TATSynEdit) then
       TATSynEdit(edit).Invalidate;
  end;
end;
```

в EdList всегда именно едиторы. так что-
```
for i:= 0 to Ed.List.Count-1 do
  TATSynEdit(EdList[i]).Invalidate;
```

**Comment by Alexey-T** [comment]
AFAIK Ed.Invalidate перерисует только то что есть в памяти едитора- оно не обновит данные из адаптера. Так что лучше делать Ed.Update (это мой метод, не LCL)

**Comment by AlekId** [comment]
> AFAIK Ed.Invalidate перерисует только то что есть в памяти едитора- оно не обновит данные из адаптера
поглядим

> нельзя так делать- эта ф-ця не должна делать побочные эфекты
пока так. У вас нет инфраструктуры для обработки события скролла.

**Comment by AlekId** [comment]
[cudatext.zip](https://github.com/Alexey-T/ATSynEdit_Ex/files/3145039/cudatext.zip)

**Comment by Alexey-T** [comment]
>нет инфраструктуры для обработки события скролла.

 OnEditorScroll в адаптере надо добавить- в базовом классе уже есть
